
import           Test.Hspec

import           TestArgInterface.TestModsMapper.TestRifleModsMapper
import           TestArgInterface.TestModsMapper.TestShotgunModsMapper
import           TestArgInterface.TestModsMapper.TestMeleeModsMapper
import           TestArgInterface.TestModsMapper.TestPistolModsMapper
import           TestArgInterface.TestWeaponDetailsIdentifier

import           TestParsing.TestParsingPrimaryWeapons
import           TestParsing.TestParsingSecondaryWeapons
import           TestParsing.TestParsingMeleeWeapons

main :: IO ()
main = hspec $ do

  describe "ArgInterface.ModsMapper.RifleModsMapper" $ do
    testRifleModsMapper
    testPistolModsMapper
    testMeleeModsMapper
    testShotgunModsMapper
    testWeaponDetailsIdentifier

  describe "Parsing Primary_Weapons" $ do
    testParsingAmprex
    testParsingFulmin_Auto
    testParsingCernos
    testParsingScourge
    testParsingDera_Vandal
    testParsingVulkar
    testParsingRakta_Cernos
    testParsingSupra
    testParsingSecura_Penta
    testParsingDex_Sybaris
    testParsingTiberon
    testParsingMk1Braton
    testParsingSancti_Tigris
    testParsingBoltor
    testParsingDera
    testParsingLatron_Prime
    testParsingDread
    testParsingVectis
    testParsingBurston_Prime
    testParsingMiter
    testParsingSynapse
    testParsingPrisma_Gorgon
    testParsingFlux_Rifle
    testParsingDrakgoon
    testParsingBurston
    testParsingHarpak
    testParsingKarak
    testParsingZenith
    testParsingPrisma_Grakata
    testParsingAttica
    testParsingQuartakk
    testParsingDaikyu
    testParsingTorid
    testParsingFerrox
    testParsingQuanta_Vandal
    testParsingLenz
    testParsingBraton_Vandal
    testParsingGorgon_Wraith
    testParsingConvectrix
    testParsingPanthera
    testParsingMk1Paris_Uncharged
    testParsingSoma_Prime
    testParsingParis_Prime
    testParsingIgnis_Wraith
    testParsingQuanta
    testParsingArca_Plasmor
    testParsingCorinth
    testParsingIgnis
    testParsingFulmin_Semi_Auto
    testParsingLatron_Wraith
    testParsingAstilla
    testParsingExergis
    testParsingCernos_Prime
    testParsingSnipetron
    testParsingRubico_Prime
    testParsingSybaris
    testParsingTetra
    testParsingGlaxion_Vandal
    testParsingBuzlok
    testParsingMk1Paris_Charged
    testParsingKohm
    testParsingGrakata
    testParsingMk1Strun
    testParsingSybaris_Prime
    testParsingVectis_Prime
    testParsingTonkor
    testParsingBoltor_Prime
    testParsingHema
    testParsingSoma
    testParsingMutalist_Cernos
    testParsingParacyst
    testParsingMutalist_Quanta
    testParsingSnipetron_Vandal
    testParsingTelos_Boltor
    testParsingSobek
    testParsingZhuge
    testParsingGlaxion
    testParsingPhantasma
    testParsingZarr
    testParsingArgonak
    testParsingSynoid_Simulor
    testParsingPrisma_Tetra
    testParsingStrun_Wraith
    testParsingOpticor
    testParsingGrinlok
    testParsingTigris_Prime
    testParsingPenta
    testParsingJavlok
    testParsingOgris
    testParsingBaza
    testParsingParis
    testParsingGorgon
    testParsingTenora
    testParsingNagantaka
    testParsingStradavar_Prime
    testParsingSupra_Vandal
    testParsingLanka
    testParsingSimulor
    testParsingOpticor_Vandal
    testParsingLatron
    testParsingHek
    testParsingBoar
    testParsingPrisma_Grinlok
    testParsingKarak_Wraith
    testParsingRubico
    testParsingBraton_Prime
    testParsingVulkar_Wraith
    testParsingVeldt
    testParsingVaykor_Hek
    testParsingHind
    testParsingBraton
    testParsingStrun
    testParsingTiberon_Prime
    testParsingBoar_Prime
    testParsingStradavar
    testParsingBattacor
    testParsingPhage
    testParsingTigris

  describe "Parsing Secondary_Weapons" $ do
    testParsingTelos_Akbolto
    testParsingViper_Wraith
    testParsingKitgun_Tombfinger_Haymaker_Splat
    testParsingSweeper_Prime
    testParsingDeth_Machine_Rifle
    testParsingRakta_Ballistica
    testParsingPrisma_Angstrum
    testParsingAkjagara_Prime
    testParsingAkbronco_Prime
    testParsingTwin_Gremlins
    testParsingBallistica_Prime
    testParsingViper
    testParsingKunai
    testParsingMultron
    testParsingAkvasto
    testParsingAkbronco
    testParsingPyrana_Prime
    testParsingOcucor
    testParsingAkmagnus
    testParsingStug
    testParsingSecura_Dual_Cestra
    testParsingKraken
    testParsingAksomati
    testParsingPrisma_Twin_Gremlins
    testParsingBallistica
    testParsingCastanas
    testParsingTwin_Rogga
    testParsingTazicor
    testParsingKnell
    testParsingBrakk
    testParsingPandero
    testParsingAklex
    testParsingSicarus_Prime
    testParsingMarelok
    testParsingAfuris
    testParsingSeer
    testParsingVulcax
    testParsingDual_Cestra
    testParsingAkstiletto_Prime
    testParsingVasto_Prime
    testParsingPox
    testParsingAkjagara
    testParsingLato_Vandal
    testParsingHikou_Prime
    testParsingLex_Prime
    testParsingPrisma_Burst_Laser
    testParsingZylok
    testParsingBolto
    testParsingAklex_Prime
    testParsingKulstar
    testParsingDespair
    testParsingTwin_Kohmak
    testParsingMk1Furis
    testParsingSpira_Prime
    testParsingTwin_Vipers
    testParsingFuris
    testParsingPyrana
    testParsingZakti
    testParsingLato_Prime
    testParsingDeconstructor
    testParsingSicarus
    testParsingLaser_Rifle
    testParsingGammacor
    testParsingAklato
    testParsingMk1Kunai
    testParsingAcrid
    testParsingSynoid_Gammacor
    testParsingLex
    testParsingBronco_Prime
    testParsingVasto
    testParsingTysis
    testParsingLato
    testParsingBronco
    testParsingEmbolist
    testParsingArtax
    testParsingCryotra
    testParsingAkvasto_Prime
    testParsingArca_Scisco
    testParsingAzima
    testParsingAtomos
    testParsingAkbolto_Prime
    testParsingDual_Toxocyst
    testParsingSpira
    testParsingVaykor_Marelok
    testParsingAngstrum
    testParsingTwin_Vipers_Wraith
    testParsingHikou
    testParsingMagnus
    testParsingStubba
    testParsingPrime_Laser_Rifle
    testParsingVulklok
    testParsingDex_Furis
    testParsingDetron
    testParsingSonicor
    testParsingTalons
    testParsingCycron
    testParsingAkstiletto
    testParsingAkbolto
    testParsingKohmak
    testParsingPlinx
    testParsingAkzani
    testParsingHystrix
    testParsingNukor
    testParsingStaticor
    testParsingBurst_Laser
    testParsingCestra
    testParsingFusilai
    testParsingStinger
    testParsingTwin_Grakatas
    testParsingDeconstructor_Prime
    testParsingEuphona_Prime
    testParsingSweeper
    testParsingSpectra
    testParsingSancti_Castanas
    testParsingMara_Detron

  describe "Parsing Melee_Weapons" $ do
    testParsingDex_Dakra
    testParsingGalatine_Prime
    testParsingAnku
    testParsingAnkyros_Prime
    testParsingSynoid_Heliocor
    testParsingLecta
    testParsingDual_Kamas
    testParsingFalcor
    testParsingPrisma_Dual_Cleavers
    testParsingRedeemer
    testParsingAmphis
    testParsingJaw_Sword
    testParsingKronen_Prime
    testParsingTelos_Boltace
    testParsingProva
    testParsingHeat_Dagger
    testParsingDestreza
    testParsingTekko
    testParsingAnkyros
    testParsingDestreza_Prime
    testParsingDual_Kamas_Prime
    testParsingAckAndBrunt
    testParsingNami_Skyla_Prime
    testParsingMire
    testParsingKorrudo
    testParsingJat_Kittag
    testParsingSydon
    testParsingTonbo
    testParsingNinkondi
    testParsingNami_Skyla
    testParsingFurax_Wraith
    testParsingEndura
    testParsingBo
    testParsingPlague_KripathShtungEkwana_Jai_II
    testParsingRedeemer_Prime
    testParsingCaustacyst
    testParsingTatsu
    testParsingTipedo
    testParsingReaper_Prime
    testParsingJat_Kusar
    testParsingDual_Zoren
    testParsingEther_Daggers
    testParsingOrthos
    testParsingShaku
    testParsingMk1Bo
    testParsingFang_Prime
    testParsingGuandao
    testParsingSerro
    testParsingKaryst
    testParsingScindo_Prime
    testParsingGram_Prime
    testParsingRakta_Dark_Dagger
    testParsingSheev
    testParsingDual_Skana
    testParsingGunsen
    testParsingFragor
    testParsingBo_Prime
    testParsingDual_Heat_Swords
    testParsingVenka
    testParsingLesion
    testParsingDual_Cleavers
    testParsingSkana_Prime
    testParsingOrvius
    testParsingEther_Sword
    testParsingCassowar
    testParsingAtterax
    testParsingPlasma_Sword
    testParsingFragor_Prime
    testParsingWar
    testParsingGlaive_Prime
    testParsingSarpa
    testParsingCeramic_Dagger
    testParsingBroken_War
    testParsingHeat_Sword
    testParsingEther_Reaper
    testParsingMachete
    testParsingNikana
    testParsingGalvacord
    testParsingCobraAndCrane
    testParsingBroken_Scepter
    testParsingParacesis
    testParsingKesheg
    testParsingDark_Sword
    testParsingFurax
    testParsingFang
    testParsingTwin_Basolk
    testParsingDragon_Nikana
    testParsingPupacyst
    testParsingSigmaAndOctantis
    testParsingPangolin_Sword
    testParsingSancti_Magistar
    testParsingHate
    testParsingKama
    testParsingGlaive
    testParsingKestrel
    testParsingBoltace
    testParsingMagistar
    testParsingNikana_Prime
    testParsingSkiajati
    testParsingTwin_Krohkur
    testParsingGazal_Machete
    testParsingPrisma_Skana
    testParsingKogake_Prime
    testParsingHirudo
    testParsingVenka_Prime
    testParsingMk1Furax
    testParsingHalikar
    testParsingSibear
    testParsingWolf_Sledge
    testParsingScindo
    testParsingLacera
    testParsingDark_SplitSword
    testParsingKronen
    testParsingObex
    testParsingMios
    testParsingDual_Raza
    testParsingCerata
    testParsingRipkas
    testParsingVolnus
    testParsingGalatine
    testParsingNami_Solo
    testParsingTipedo_Prime
    testParsingOrthos_Prime
    testParsingOhma
    testParsingPrisma_Obex
    testParsingArca_Titron
    testParsingKreska
    testParsingOkina
    testParsingKrohkur
    testParsingSecura_Lecta
    testParsingLandslide
    testParsingProva_Vandal
    testParsingSkana
    testParsingPrisma_Machete
    testParsingDark_Dagger
    testParsingVaykor_Sydon
    testParsingSilvaAndAegis
    testParsingZenistar
    testParsingKogake
    testParsingScoliac
    testParsingDual_Keres
    testParsingDakra_Prime
    testParsingSilvaAndAegis_Prime
    testParsingHeliocor
    testParsingGram
    testParsingCronus
    testParsingMachete_Wraith
    testParsingDual_Ichor
    testParsingDual_Ether
