{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : ArgInterface.MeleeWeapons
-- Maintainer  : verystable@proton.com
-- Stability   : experimental
--
-- This module contains all useable Melee weapons' name, linked to 'warframe-builder-data/Melee_Weapons'

module ArgInterface.MeleeWeapons
  ( listOfAvailableMelees
  )
where

import           ClassyPrelude

-- | List of available melee weapons. This list has to be modified
--   if a weapon is added to the 'warframe-autobuilder-data/Melee_Weapons' folder.
listOfAvailableMelees :: [Text]
listOfAvailableMelees =
  [ "Ack_&_Brunt"
  , "Amphis"
  , "Anku"
  , "Ankyros"
  , "Ankyros_Prime"
  , "Arca_Titron"
  , "Atterax"
  , "Bo"
  , "Boltace"
  , "Bo_Prime"
  , "Broken_Scepter"
  , "Broken_War"
  , "Cassowar"
  , "Caustacyst"
  , "Ceramic_Dagger"
  , "Cerata"
  , "Cobra_&_Crane"
  , "Cronus"
  , "Dakra_Prime"
  , "Dark_Dagger"
  , "Dark_Split-Sword"
  , "Dark_Sword"
  , "Destreza"
  , "Destreza_Prime"
  , "Dex_Dakra"
  , "Dragon_Nikana"
  , "Dual_Cleavers"
  , "Dual_Ether"
  , "Dual_Heat_Swords"
  , "Dual_Ichor"
  , "Dual_Kamas"
  , "Dual_Kamas_Prime"
  , "Dual_Keres"
  , "Dual_Raza"
  , "Dual_Skana"
  , "Dual_Zoren"
  , "Endura"
  , "Ether_Daggers"
  , "Ether_Reaper"
  , "Ether_Sword"
  , "Falcor"
  , "Fang"
  , "Fang_Prime"
  , "Fragor"
  , "Fragor_Prime"
  , "Furax"
  , "Furax_Wraith"
  , "Galatine"
  , "Galatine_Prime"
  , "Galvacord"
  , "Gazal_Machete"
  , "Glaive"
  , "Glaive_Prime"
  , "Gram"
  , "Gram_Prime"
  , "Guandao"
  , "Gunsen"
  , "Halikar"
  , "Hate"
  , "Heat_Dagger"
  , "Heat_Sword"
  , "Heliocor"
  , "Hirudo"
  , "Jat_Kittag"
  , "Jat_Kusar"
  , "Jaw_Sword"
  , "Kama"
  , "Karyst"
  , "Kesheg"
  , "Kestrel"
  , "Kogake"
  , "Kogake_Prime"
  , "Korrudo"
  , "Kreska"
  , "Krohkur"
  , "Kronen"
  , "Kronen_Prime"
  , "Lacera"
  , "Lecta"
  , "Lesion"
  , "Machete"
  , "Machete_Wraith"
  , "Magistar"
  , "Mios"
  , "Mire"
  , "Mk1-Bo"
  , "Mk1-Furax"
  , "Nami_Skyla"
  , "Nami_Skyla_Prime"
  , "Nami_Solo"
  , "Nikana"
  , "Nikana_Prime"
  , "Ninkondi"
  , "Obex"
  , "Ohma"
  , "Okina"
  , "Orthos"
  , "Orthos_Prime"
  , "Orvius"
  , "Pangolin_Sword"
  , "Paracesis"
  , "Plasma_Sword"
  , "Prisma_Dual_Cleavers"
  , "Prisma_Machete"
  , "Prisma_Obex"
  , "Prisma_Skana"
  , "Prova"
  , "Prova_Vandal"
  , "Pupacyst"
  , "Rakta_Dark_Dagger"
  , "Reaper_Prime"
  , "Redeemer"
  , "Redeemer_Prime"
  , "Ripkas"
  , "Sancti_Magistar"
  , "Sarpa"
  , "Scindo"
  , "Scindo_Prime"
  , "Scoliac"
  , "Secura_Lecta"
  , "Serro"
  , "Shaku"
  , "Sheev"
  , "Sibear"
  , "Sigma_&_Octantis"
  , "Silva_&_Aegis"
  , "Silva_&_Aegis_Prime"
  , "Skana"
  , "Skana_Prime"
  , "Skiajati"
  , "Sydon"
  , "Synoid_Heliocor"
  , "Tatsu"
  , "Tekko"
  , "Telos_Boltace"
  , "Tipedo"
  , "Tipedo_Prime"
  , "Tonbo"
  , "Twin_Basolk"
  , "Twin_Krohkur"
  , "Vaykor_Sydon"
  , "Venka"
  , "Venka_Prime"
  , "Volnus"
  , "War"
  , "Wolf_Sledge"
  , "Zenistar"
  , "Plague_Kripath+Shtung+Ekwana_Jai_II"
  , "Landslide"
  ]
