{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : ArgInterface.PistolWeapons
-- Maintainer  : verystable@proton.com
-- Stability   : experimental
--
-- This module contains all the useable pistol weapon data
-- from 'warframe-autobuilder-data/Secondary_Weapons' folder.

module ArgInterface.PistolWeapons where

import           ClassyPrelude

-- | List of available secondary weapons. This list has to be modified
--   if a weapon is added to the 'warframe-builder-data/Secondary_Weapons' folder.
listOfAvailablePistols :: [Text]
listOfAvailablePistols =
  [ "Acrid"
  , "Afuris"
  , "Akbolto"
  , "Akbolto_Prime"
  , "Akbronco"
  , "Akbronco_Prime"
  , "Akjagara"
  , "Akjagara_Prime"
  , "Aklato"
  , "Aklex"
  , "Aklex_Prime"
  , "Akmagnus"
  , "Aksomati"
  , "Akstiletto"
  , "Akstiletto_Prime"
  , "Akvasto"
  , "Akvasto_Prime"
  , "Akzani"
  , "Angstrum"
  , "Arca_Scisco"
  , "Artax"
  , "Atomos"
  , "Azima"
  , "Ballistica"
  , "Ballistica_Prime"
  , "Bolto"
  , "Brakk"
  , "Bronco"
  , "Bronco_Prime"
  , "Burst_Laser"
  , "Castanas"
  , "Cestra"
  , "Cryotra"
  , "Cycron"
  , "Deconstructor"
  , "Deconstructor_Prime"
  , "Despair"
  , "Deth_Machine_Rifle"
  , "Detron"
  , "Dex_Furis"
  , "Dual_Cestra"
  , "Dual_Toxocyst"
  , "Embolist"
  , "Euphona_Prime"
  , "Furis"
  , "Fusilai"
  , "Gammacor"
  , "Hikou"
  , "Hikou_Prime"
  , "Hystrix"
  , "Knell"
  , "Kohmak"
  , "Kraken"
  , "Kulstar"
  , "Kunai"
  , "Laser_Rifle"
  , "Lato"
  , "Lato_Prime"
  , "Lato_Vandal"
  , "Lex"
  , "Lex_Prime"
  , "Magnus"
  , "Mara_Detron"
  , "Marelok"
  , "Mk1-Furis"
  , "Mk1-Kunai"
  , "Multron"
  , "Nukor"
  , "Ocucor"
  , "Pandero"
  , "Plinx"
  , "Pox"
  , "Prime_Laser_Rifle"
  , "Prisma_Angstrum"
  , "Prisma_Burst_Laser"
  , "Prisma_Twin_Gremlins"
  , "Pyrana"
  , "Pyrana_Prime"
  , "Rakta_Ballistica"
  , "Sancti_Castanas"
  , "Secura_Dual_Cestra"
  , "Seer"
  , "Sicarus"
  , "Sicarus_Prime"
  , "Sonicor"
  , "Spectra"
  , "Spira"
  , "Spira_Prime"
  , "Staticor"
  , "Stinger"
  , "Stubba"
  , "Stug"
  , "Sweeper"
  , "Sweeper_Prime"
  , "Synoid_Gammacor"
  , "Talons"
  , "Tazicor"
  , "Telos_Akbolto"
  , "Twin_Grakatas"
  , "Twin_Gremlins"
  , "Twin_Kohmak"
  , "Twin_Rogga"
  , "Twin_Vipers"
  , "Twin_Vipers_Wraith"
  , "Tysis"
  , "Vasto"
  , "Vasto_Prime"
  , "Vaykor_Marelok"
  , "Viper"
  , "Viper_Wraith"
  , "Vulcax"
  , "Vulklok"
  , "Zakti"
  , "Zylok"
  , "Kitgun_Tombfinger_Haymaker_Splat"
  ]
