{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : ArgInterface.PistolWeapons
-- Maintainer  : verystable@proton.com
-- Stability   : experimental
--
-- This module contains all the useable rifle weapon data
-- from 'warframe-autobuilder-data/Primary_Weapons' folder.

module ArgInterface.RifleWeapons where

import           ClassyPrelude

-- | List of available primary weapons. This list has to be modified
--   if a weapon is added to the 'warframe-autobuilder-data/Primary_Weapons' folder.
listOfAvailableRifles :: [Text]
listOfAvailableRifles =
  [ "Acceltra"
  , "Amprex"
  , "Argonak"
  , "Attica"
  , "Battacor"
  , "Baza"
  , "Boltor"
  , "Boltor_Prime"
  , "Braton"
  , "Braton_Prime"
  , "Braton_Vandal"
  , "Burston"
  , "Burston_Prime"
  , "Buzlok"
  , "Cernos"
  , "Cernos_Prime"
  , "Daikyu"
  , "Dera"
  , "Dera_Vandal"
  , "Dex_Sybaris"
  , "Dread"
  , "Ferrox"
  , "Flux_Rifle"
  , "Fulmin_Auto"
  , "Fulmin_Semi_Auto"
  , "Glaxion"
  , "Glaxion_Vandal"
  , "Gorgon"
  , "Gorgon_Wraith"
  , "Grakata"
  , "Grinlok"
  , "Harpak"
  , "Hema"
  , "Hind"
  , "Ignis"
  , "Ignis_Wraith"
  , "Javlok"
  , "Karak"
  , "Karak_Wraith"
  , "Lanka"
  , "Latron"
  , "Latron_Prime"
  , "Latron_Wraith"
  , "Lenz"
  , "Miter"
  , "Mk1-Braton"
  , "Mk1-Paris"
  , "Mutalist_Cernos"
  , "Mutalist_Quanta"
  , "Nagantaka"
  , "Ogris"
  , "Opticor"
  , "Opticor_Vandal"
  , "Panthera"
  , "Paracyst"
  , "Paris"
  , "Paris_Prime"
  , "Penta"
  , "Prisma_Gorgon"
  , "Prisma_Grakata"
  , "Prisma_Grinlok"
  , "Prisma_Tetra"
  , "Quanta"
  , "Quanta_Vandal"
  , "Quartakk"
  , "Rakta_Cernos"
  , "Rubico"
  , "Rubico_Prime"
  , "Scourge"
  , "Secura_Penta"
  , "Simulor"
  , "Snipetron"
  , "Snipetron_Vandal"
  , "Soma"
  , "Soma_Prime"
  , "Stradavar"
  , "Stradavar_Prime"
  , "Supra"
  , "Supra_Vandal"
  , "Sybaris"
  , "Sybaris_Prime"
  , "Synapse"
  , "Synoid_Simulor"
  , "Telos_Boltor"
  , "Tenora"
  , "Tetra"
  , "Tiberon"
  , "Tiberon_Prime"
  , "Tonkor"
  , "Torid"
  , "Vectis"
  , "Vectis_Prime"
  , "Veldt"
  , "Vulkar"
  , "Vulkar_Wraith"
  , "Zarr"
  , "Zenith"
  , "Zhuge"
  ]
